[tool.black]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
float_to_top = true
force_sort_within_sections = true
order_by_type = false
sections = ["STDLIB", "THIRDPARTY", "FIRSTPARTY"]
src_paths = ["backend"]
known_first_party = ["backend"]
combine_as_imports = true
