"""Export Postgres rows (user + story) to a D1-loadable SQL file.

One-shot migration helper for the Cloudflare move. Reads via asyncpg and emits
INSERT statements with SQLite-compatible literals.

    DATABASE_URL='postgresql+asyncpg://postgres:postgres@localhost:5433/tih_dev' \
      python backend/scripts/export_to_d1.py > backend/d1/seed.sql

IMPORTANT: run this against the *container* database. On this machine
localhost:5433 may resolve to a different Postgres — prefer piping through
`docker compose exec`, or verify the row count before trusting the output.

Datetime columns become ISO-8601 TEXT and booleans become 0/1, matching
backend/d1/schema.sql.
"""

from __future__ import annotations

import asyncio
import datetime as dt
import os
import sys

import asyncpg

USER_COLS = (
    "id", "email", "hashed_password", "full_name",
    "is_author", "is_active", "created_at",
)

STORY_COLS = (
    "id", "title", "slug", "canonical_url", "source_url", "content_hash",
    "content_source", "meta_description", "content", "excerpt",
    "cover_image_url", "status", "author_notes", "content_warning",
    "view_count", "read_time_minutes", "author_id",
    "created_at", "updated_at", "published_at", "search_vector",
)


def lit(value: object) -> str:
    """Render a Python value as a SQLite literal."""
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "1" if value else "0"
    if isinstance(value, (int, float)):
        return str(value)
    if isinstance(value, dt.datetime):
        # Normalize to naive ISO-8601 UTC — schema.sql stores timestamps as TEXT.
        return "'" + value.replace(tzinfo=None).isoformat(sep=" ") + "'"
    text = str(value)
    # SQLite escapes a single quote by doubling it. Nothing else needs escaping.
    return "'" + text.replace("'", "''") + "'"


def emit(table: str, cols: tuple[str, ...], rows: list[asyncpg.Record]) -> None:
    if not rows:
        print(f"-- {table}: no rows", file=sys.stderr)
        return
    collist = ", ".join(cols)
    for row in rows:
        # Enum columns arrive as Python enums or str; str() gives the value name.
        values = []
        for col in cols:
            v = row[col]
            if col == "status" and v is not None:
                v = str(v).lower().rsplit(".", 1)[-1]
            values.append(lit(v))
        print(f"INSERT INTO {table} ({collist}) VALUES ({', '.join(values)});")
    print(f"-- {table}: {len(rows)} rows", file=sys.stderr)


async def main() -> None:
    raw = os.environ.get("DATABASE_URL", "")
    dsn = raw.replace("postgresql+asyncpg://", "postgresql://")
    if not dsn:
        sys.exit("DATABASE_URL is required")
    conn = await asyncpg.connect(dsn)
    try:
        users = await conn.fetch(f"SELECT {', '.join(USER_COLS)} FROM \"user\" ORDER BY id")
        stories = await conn.fetch(f"SELECT {', '.join(STORY_COLS)} FROM story ORDER BY id")
    finally:
        await conn.close()

    print("-- Generated by backend/scripts/export_to_d1.py")
    print("PRAGMA defer_foreign_keys = true;")
    emit("user", USER_COLS, users)
    emit("story", STORY_COLS, stories)


if __name__ == "__main__":
    asyncio.run(main())
