"""Rewrite Substack CDN image URLs in story HTML to self-hosted copies.

Reads the D1 export, maps every `substackcdn.com/image/fetch/...` URL to a local
`/essay-images/<sha1>.webp`, and emits the UPDATE statements.

Why this exists: all 73 essays hotlinked their images from Substack's CDN,
including the og:image used for social previews. That made the archive depend on
Substack's infrastructure — if they change CDN rules or the account goes away,
every essay loses its images.

Key detail: Substack emits ~8.6 srcset variants per image, all wrapping the SAME
upstream S3 original after the transform segment. The mapping key is that
decoded original URL, so every variant of an image collapses onto one local file.

    python3 backend/scripts/rehost_essay_images.py > /tmp/rehost.sql

`content_hash` is deliberately NOT recomputed: it hashes normalized TEXT, not
markup (see html_sanitize.content_hash), so swapping image hosts must not change
it. If it did, the next sync would see every row as "edited" and rewrite all 73.
"""

from __future__ import annotations

import hashlib
import json
import re
import sys
import urllib.parse

FETCH_RE = re.compile(r"https://substackcdn\.com/image/fetch/[^\"'\s>\\]+")
ORIGINAL_RE = re.compile(r"/image/fetch/[^/]*/(https?%3A%2F%2F.+)$")


def local_name(original_url: str) -> str:
    """Stable local filename for an upstream image (matches the download step)."""
    return hashlib.sha1(original_url.encode()).hexdigest()[:16] + ".webp"


def to_local(cdn_url: str) -> str | None:
    match = ORIGINAL_RE.search(cdn_url)
    if not match:
        return None
    original = urllib.parse.unquote(match.group(1))
    return "/essay-images/" + local_name(original)


def sql_escape(text: str) -> str:
    return text.replace("'", "''")


def main() -> None:
    raw = open("/tmp/stories.json", encoding="utf-8").read()
    match = re.search(r'"results":\s*(\[.*\])\s*,\s*"success"', raw, re.S)
    if not match:
        sys.exit("could not parse /tmp/stories.json")
    rows = json.loads(match.group(1))

    available = set(open("/tmp/available.txt", encoding="utf-8").read().split())
    rewritten = skipped = 0

    print("-- Generated by backend/scripts/rehost_essay_images.py")
    for row in rows:
        content = row.get("content") or ""
        cover = row.get("cover_image_url") or ""
        new_content = content
        for cdn in set(FETCH_RE.findall(content)):
            local = to_local(cdn)
            # Only rewrite when the file actually downloaded, so a failed fetch
            # leaves the working Substack URL in place rather than a dead link.
            if local and local.rsplit("/", 1)[-1] in available:
                new_content = new_content.replace(cdn, local)
                rewritten += 1
            else:
                skipped += 1

        new_cover = cover
        if cover.startswith("https://substackcdn.com/image/fetch/"):
            local = to_local(cover)
            if local and local.rsplit("/", 1)[-1] in available:
                new_cover = local

        if new_content != content or new_cover != cover:
            print(
                f"UPDATE story SET content='{sql_escape(new_content)}', "
                f"cover_image_url='{sql_escape(new_cover)}' WHERE id={row['id']};"
            )

    print(f"-- urls rewritten: {rewritten}, left on substack: {skipped}", file=sys.stderr)


if __name__ == "__main__":
    main()
